platform :ios, '10.0'

target 'StromControllerIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftSocket'
  pod 'FontAwesome.swift'

  target 'StromControllerIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StromControllerIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
